### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by joachimvh** [joachimvh/community-server-article#2]
Updated most sections. Summary below:

#### Abstract
Fully rewritten. Kept RV comments because I wasn't sure if they were actually answered.

#### 1. Introduction
Unchanged. Not really an idea where to best go with this seeing as I only interact with the purely technical side and am not really knowledgeable about all the other aspects.

#### 2. Requirements
Slightly extended. Kept some comments where I didn't know what to do with them. Also moved references to existing implementations here (made more sense than in related work to me, but I might be wrong). Not sure what more to say about them besides "not flexible enough".

It's also difficult to gauge what exactly the requirements should be since I mostly started making the server when decisions were already made and I'm less aware of what is needed in the ecosystem.

#### 3. Related work
Added some text about the core technologies. Not sure what more needs to be said about them or what else is relevant.

#### 4. Architecture
Largely rewritten. The most extensive chapter (since here I actually know what I'm talking about 😉 ).

#### 5. Configuration
Slightly extended and restructured.

#### 6. Usage
Slightly extended and updated.
Not sure what was meant with "all apps that work on the server". Do we also want to start linking Solid client applications, even though they already existed without CSS?

#### 7. Conclusions
Slightly changed.

**Comment by RubenVerborgh** [comment]
A major apology for the extremely long reviewing period on this one.
Abstract proposal here: bec06a30ad04722ea70718b0d3fffcfabf21babb

**Comment by RubenVerborgh** [comment]
Reviewing comments have been added. Might still write some text for intro etc. at a later point; just want to make sure the meat is ready to go first.
